<?php namespace wpenv ?>

production: &default
  AUTH_KEY:         <?php env("WP_AUTH_KEY") ?>
  SECURE_AUTH_KEY:  <?php env("WP_SECURE_AUTH_KEY") ?>
  LOGGED_IN_KEY:    <?php env("WP_LOGGED_IN_KEY") ?>
  NONCE_KEY:        <?php env("WP_NONCE_KEY") ?>
  AUTH_SALT:        <?php env("WP_AUTH_SALT") ?>
  SECURE_AUTH_SALT: <?php env("WP_SECURE_AUTH_SALT") ?>
  LOGGED_IN_SALT:   <?php env("WP_LOGGED_IN_SALT") ?>
  NONCE_SALT:       <?php env("WP_NONCE_SALT") ?>

  WP_LANG: ""
  WP_DEBUG: false

development:
  <<: *default

  # get values from:
  # https://api.wordpress.org/secret-key/1.1/salt/
  AUTH_KEY:
  SECURE_AUTH_KEY:
  LOGGED_IN_KEY:
  NONCE_KEY:
  AUTH_SALT:
  SECURE_AUTH_SALT:
  LOGGED_IN_SALT:
  NONCE_SALT:
